### ISSUE TITLE
Syntax specific color schemes not applied correctly on startup

### ISSUE THREAD

**Issue by themilkman** [absop/RainbowBrackets#14]
Hi there,

I see a strange behavior with syntax specific color schemes in combination with RainbowBrackets.
The details are described in:
sublimehq/sublime_text#4000
I am yet not sure if it is only my setup but the problem described stopped reproducible when I disable the RB package.

Is someone else able to reproduce it?

Cheers and thanks for all the rainbows! :)

**Comment by absop** [comment]
I have found some strange rendering action on regions added by `add_regions` before, on ST4, as the following GIF shows, but it is hard to reproduce. 

In the screen screenshots, I did nothing but only resize the `window`, and we can see that, in the `view`, some regions' colors are changed irregularly. Or even I just scroll up and down the focus of view, there are some regions be rendered incorrectly too.

To reproduce this bug on ST4 with **RB**,  you need a large `scheme` source code, maybe at least 2000 lines code, I have tried it on a large `JSON` file, but I didn't reproduce it on that file. 

I thing this is an optimizing error of the `add_regions` API, which is supplied by ST to change region's rendering dynamically. It work well on view which use `add_regions` less, but in a view which use `add_regions` to add a large number of region, it might reproduce this strange problem.
![add_regions](https://user-images.githubusercontent.com/32818900/112965174-97e05b00-917b-11eb-876b-ef0b462bf2f5.gif)
![sblime_text add_regions](https://user-images.githubusercontent.com/32818900/112968249-b1cf6d00-917e-11eb-869a-db9016ca00e0.png)

**Comment by themilkman** [comment]
Ouh, this looks indeed weird..!

But - I am a bit confused - do you think this is really related to my mentioned issue?

**Comment by absop** [comment]
> 

Aha, It's a bug of RB. **syntax specific color schemes** are not currently considered.

**Comment by absop** [comment]
@themilkman  The latest version of the mater branch should fix this issue, can you give it a try?

**Comment by themilkman** [comment]
Hi @absop , seems to work now! 
(I had to struggle with some other Theme related stuff after the new ST build of last night, so a bit another setup).

Thank you very much for taking a look into it an create a fix!! :pray:  :-)

**Comment by themilkman** [comment]
Huh, I have no I idea what happened/what I did but my impression is that RBB was disabled when I tested it and my mind was in another dimension. Now I realized that the issue still persists and the behavior is even more weird.
It seems to always recreate the CS, gets reset quite often and the corners of the brackets have little white sections.
![rainbow](https://user-images.githubusercontent.com/1582492/154072685-faf73dde-6c8a-445a-96de-d64e015ed0d3.png)

Sorry for my confusion... :-/

**Comment by absop** [comment]
@themilkman Can you provide a larger screenshot?

**Comment by themilkman** [comment]
The screenshot below shows an JS file on the left (default with CS applied) and the same CS as Syntax specific on a ruby file on the right:

![rainbow2](https://user-images.githubusercontent.com/1582492/154219568-a10cc919-8d02-4021-8da2-71d2cd2bd1ed.png)


For the records: https://github.com/themilkman/sublime-toxinated is the CS

**Comment by absop** [comment]
Can you put your code and "rainbow_colors" setting here?

**Comment by themilkman** [comment]
Sure

```JSONC
/*
  RainbowBrackets user settings in here override the default
*/
{
    "default_config": {
        "bracket_pairs": {
            "(": ")",
            "[": "]",
            "{": "}"
        },
        "coloring": false,
        "enabled": true,
        "ignored_scopes": [
            "comment",
            "string",
            "constant"
        ],
        "rainbow_colors": [
            "#FFFFFF",
            "#FF6A00",
            "#FFD800",
            "#00FF00",
            "#0094FF",
            "#0041FF",
            "#7D00E5"
        ],
        "mismatch_color": "#FF0000"
    },
    "syntax_specific": {
        "Ruby": {
            "bracket_pairs": {
                "(": ")",
                "{": "}",
                "[": "]",
            },
            "extensions": [
                ".haml",
                ".slim",
                ".rb",
                ".erb",
            ],
            "ignored_scopes": [
                "comment",
                "string"
            ]
        },

        "JSON": {
            "bracket_pairs": {
                "{": "}",
                "[": "]",
            },

            "extensions": [
                ".json",
                ".sublime-settings",
                ".sublime-menu",
                ".sublime-build",
                ".sublime-keymap",
                ".sublime-commands",
                ".sublime-theme",
                ".sublime-color-scheme"
            ],

            "ignored_scopes": [
                "comment", "string"
            ]
        },
    },
}
```


Ruby.sublime-settings:

```JSONC
{
  "extensions":
  [
    "axlsx"
  ],
  "color_scheme": "Packages/User/Toxinated.sublime-color-scheme"
}

```

**Comment by absop** [comment]
I still cam't see anything unusual in the picture you gave above.
Can you describe the problem in this picture
![](https://user-images.githubusercontent.com/1582492/154219568-a10cc919-8d02-4021-8da2-71d2cd2bd1ed.png)

**Comment by absop** [comment]
Oh, I saw the white dots.
